CREATE TABLE Clean_Squat.USER
(
  UserID SERIAL NOT NULL,
  Username VARCHAR(30) UNIQUE NOT NULL,
  Password VARCHAR(128) NOT NULL,
  FirstName VARCHAR(30) NOT NULL,
  LastName VARCHAR(30)  NOT NULL,
  Role ENUM ('USER', 'SUPERVISOR', 'STAFF' ) NOT NULL,
  PRIMARY KEY (UserID)
);

CREATE TABLE Clean_Squat.BUILDING
(
  BuildingName VARCHAR(100) NOT NULL UNIQUE,
  BuildingID SERIAL NOT NULL,
  PRIMARY KEY (BuildingID)
);

CREATE TABLE Clean_Squat.SESSION
(
  SessionID SERIAL NOT NULL,
  TimeStamp TIMESTAMP NOT NULL,
  UserID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (SessionID),
  FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

CREATE TABLE Clean_Squat.RESTROOM
(
  Gender varchar(6),
  CleaningTimeStamp TIMESTAMP NOT NULL,
  RestroomID SERIAL NOT NULL,
  IsPrivate BOOLEAN NOT NULL,
  BuildingID BIGINT UNSIGNED NOT NULL,
  FloorNumber INT NOT NULL,
  RoomNumber varchar(5) NOT NULL,
  PRIMARY KEY (RestroomID),
  FOREIGN KEY (BuildingID) REFERENCES Clean_Squat.BUILDING(BuildingID)
);

CREATE TABLE Clean_Squat.RATING
(
  RatingID SERIAL NOT NULL,
  Rating INT NOT NULL,
  UserID BIGINT UNSIGNED NOT NULL,
  RestroomID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (RatingID),
  FOREIGN KEY (UserID) REFERENCES USER(UserID),
  FOREIGN KEY (RestroomID) REFERENCES RESTROOM(RestroomID)
);

CREATE TABLE Clean_Squat.ISSUEREPORT
(
  IssueID SERIAL NOT NULL,
  Description VARCHAR(2000) NOT NULL,
  CompletionStatus BOOLEAN NOT NULL,
  ReportTimeStamp TIMESTAMP NOT NULL UNIQUE,
  RestroomID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (IssueID, ReportTimeStamp),
  FOREIGN KEY (RestroomID) REFERENCES RESTROOM(RestroomID)
);

CREATE TABLE Clean_Squat.Manipulate
(
  IssueID BIGINT UNSIGNED NOT NULL,
  UserID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (IssueID, UserID),
  FOREIGN KEY (IssueID) REFERENCES ISSUEREPORT(IssueID),
  FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

