DELETE FROM Clean_Squat.SESSION WHERE SessionID;
DELETE FROM Clean_Squat.RATING WHERE RatingID;
DELETE FROM Clean_Squat.MANIPULATE WHERE IssueID;
DELETE FROM Clean_Squat.ISSUEREPORT WHERE IssueID;
DELETE FROM Clean_Squat.RESTROOM WHERE RestroomID;
DELETE FROM Clean_Squat.BUILDING WHERE BuildingID;
DELETE FROM Clean_Squat.USER WHERE UserID;